server:
  port: 8001
  servlet:
    context-path: /api

spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    cache: true
  profiles:
    active: dev
  main:
    allow-bean-definition-overriding: true

mybatis:
  configuration:
    cache-enabled: true


#logging:
#  pattern:
#    console: %d{yyyy‐MM‐dd} [%thread] %‐5level %logger{50} ‐ %msg%n

