


mybatis:
  type-aliases-package: com.wuzhiaite.javaweb.base.entity # entity别名类所在包
  mapper-locations: mybatis/mapper/*.xml    # mapper映射文件
spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    cache: true
  profiles:
    active: pro