server:
  port: 8002
  servlet:
    context-path: /

spring:
  profiles:
    include: pro-extra #加入额外的文件
  application:
    name: microserver-product #这个很重要，这在以后的服务与服务之间相互调用一般都是根据这个name
  dbsource: #多数据源配置
    master:
      driver-class-name: com.mysql.cj.jdbc.Drivergit
      url: jdbc:mysql://rm-uf6101yy6jg1qe3e8lo.mysql.rds.aliyuncs.com/com_sys?serverTimezone=UTC&useSSL=false
      password: wuzhiaite
      username: wuzhiaite
#    dbcp2:ss
#      min-idle: 5                         # 数据库连接池的最小维持连接数
#      initial-size: 5                     # 初始化连接数
#      max-total: 5                        # 最大连接数
#      max-wait-millis: 150                # 等待连接获取的最大超时时间springboot linux启动项目
  redis:
    host: 47.113.120.21
    port: 6379
    password: 123456
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 500
        min-idle: 0
    lettuce:
      shutdown-timeout: 0
  servlet:
    multipart:
      max-file-size: 2000MB
      max-request-size: 2000MB

mybatis:
  configuration:
    cache-enabled: true
  mapper-locations: /mapper/*.xml




logging:
  file:
    path: /usr/local/java/log/


uploadFilePath: /usr/local/java/upload/