server:
  port: 8002
  servlet:
    context-path: /


spring:
  application:
    name: microserver-product #这个很重要，这在以后的服务与服务之间相互调用一般都是根据这个name
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-uf6101yy6jg1qe3e8lo.mysql.rds.aliyuncs.com/com_sys?serverTimezone=GMT%2B8
    password: wuzhiaite
    username: wuzhiaite
    dbcp2:
      min-idle: 5                         # 数据库连接池的最小维持连接数
      initial-size: 5                     # 初始化连接数
      max-total: 5                        # 最大连接数
      max-wait-millis: 150                # 等待连接获取的最大超时时间
  redis:
    host: 47.113.120.21
    port: 6379
    password: 123456
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 500
        min-idle: 0
    lettuce:
      shutdown-timeout: 0





logging:
  file:
    path: /usr/local/java/log/
