server:
  port: 8001
  servlet:
    context-path: /

spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    cache: true
  profiles:
    active: pro
  main:
    allow-bean-definition-overriding: true

mybatis:
  configuration:
    cache-enabled: true
