
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/java_test?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

baseconfig:
  sqlscriptpath: sql
  initscriptname: init.sql
  databaseName: java_test
  filterurl:
    - /*


logging:
  file:
    path: D:\log
