
spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    cache: true
  profiles:
    active: dev

mybatis:
  configuration:
    cache-enabled: true

