server:
  port: 8001
  servlet:
    context-path: /


spring:
  profiles:
    include:
      - dev-extra
  application:
    name: microserver-product #这个很重要，这在以后的服务与服务之间相互调用一般都是根据这个name
  dbsource:
    master:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3307/cs_db?serverTimezone=GMT%2B8
      password: root
      username: root
    slave:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3307/cmbi_boss?serverTimezone=GMT%2B8
      password: root
      username: root
  redis:
#    host: 192.168.210.128
    host: 47.113.120.21
    port: 6379
    password: 123456
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 500
        min-idle: 0
    lettuce:
      shutdown-timeout: 0
    timeout: 5000
  rabbitmq:
    host: 47.113.120.21
    port: 5672
    password: admin
    username: admin
  servlet:
    multipart: #上传配置
      max-file-size: 2000MB #最大
      max-request-size: 2000MB
  mail: #邮箱
    host: smtp.qq.com
    port: 25
    username: li656494298@foxmail.com
    password: wmtyfdyfqplmbeda
  liquibase:
    enabled: false

logging:
  file:
    path: D:\log
uploadFilePath: D:\\uploadFile\\





